// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChddVqfsph_dh22qruuG2KCM_t2CPmrKU',
    appId: '1:775461283083:web:d82f3e5ce9b7906b4d6e0e',
    messagingSenderId: '775461283083',
    projectId: 'salongly-766ea',
    authDomain: 'salongly-766ea.firebaseapp.com',
    databaseURL: 'https://salongly-766ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salongly-766ea.appspot.com',
    measurementId: 'G-NC1GGK3VJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOuN0qR5mGt7Le8zSBQwQKvH26C4RMrAQ',
    appId: '1:775461283083:android:2386a6cbd19203e74d6e0e',
    messagingSenderId: '775461283083',
    projectId: 'salongly-766ea',
    databaseURL: 'https://salongly-766ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salongly-766ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMmVEVUHauG5j0OZuJcc1-5dR5fbAYQyo',
    appId: '1:775461283083:ios:00d845889705991a4d6e0e',
    messagingSenderId: '775461283083',
    projectId: 'salongly-766ea',
    databaseURL: 'https://salongly-766ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salongly-766ea.appspot.com',
    iosClientId: '775461283083-e9g8lbjpa1jp6q2i2uiprhjbsl4vhi1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.salongly',
  );
}
